Update Cloud Function with Upload Processor
populationgenomics/sample-metadata pull request #12
Opened 2021-07-26 00:55 UTC by vivbak

Workflow is as follows
1. gVCFs and CRAMS concurrently moved.
2. Following a successful move, analysis objects are created.
3. Once analysis objects are successfully created, sequencing metadata is updated

2021-08-02 11:42 UTC, vivbak commented
Updated Workflow: 
`main.py` defines an endpoint, that when hit, formats a file object. This file object, and the associated qc_metadata is added to the sample metadata db. 
`process_backlog.py` exists to process previous batches.

2021-08-03 05:32 UTC, illusional requested changes
This is looking pretty good!

2021-08-03 05:32 UTC, illusional commented on update_sample_status/main.py
> +    internal_id_map = sapi.get_sample_id_map_by_external(project, external_id_dict)
This recently changed, so you don't need to wrap it in a dictionary anymore.

```suggestion
    internal_id_map = sapi.get_sample_id_map_by_external(project, [external_id])
```

2021-08-03 05:32 UTC, illusional commented on update_sample_status/main.py
> +    return web.Response(text=f'{external_id} lodged.')
It looks like you set `reads` to an empty array, and then set on every iteration, but I think it'd be better to not set everything against reads (as initially suggested), and instead against the different types:

- `reads` for (`.cram`)
- `gvcf` for (`.gvcf`)

If you add `'meta-field'` to the FILES_HANDLED dict, your code could look something like:

```suggestion
    # TODO: Added the QC Metadata Here. Should this be moved to sample metadata?
    meta = {'qc_metrics': qc_metadata}
    for key in FILES_HANDLED:
        reads = create_file_object(external_id, key, project, batch)
        
        field_name = FILES_HANDLED[key]['meta-field']
        meta[field_name] = reads
        meta[field_name + '_type'] = key
        
    # Update the sequencing metadata.
    update_sequence_meta(project, internal_id, status, metadata)

    return web.Response(text=f'{external_id} lodged.')
```

2021-08-03 05:32 UTC, illusional commented on update_sample_status/main.py
> +}
To address future comment.

```suggestion
FILES_HANDLED = {
    'gvcf': [{'primary': '.g.vcf.gz', 'secondary': ['.g.vcf.gz.tbi', '.g.vcf.gz.md5'], 'meta-field': 'gvcf'}],
    'cram': [{'primary': '.cram', 'secondary': ['.cram.crai', '.cram.md5'], 'meta-field': 'reads'}],
}
```

2022-06-03 03:29 UTC, closed without merging