Fix update sample status
populationgenomics/sample-metadata pull request #144
Opened 2022-02-21 00:13 UTC by vivbak

Addresses https://github.com/populationgenomics/sample-metadata/issues/4

2022-03-27 21:05 UTC, illusional requested changes

2022-03-27 21:05 UTC, illusional commented on db/python/tables/sequence.py
> +        return result['id']
This should return the ProjectID as well.

2022-03-27 21:05 UTC, illusional commented on db/python/layers/sequence.py
> +        return await self.update_status(seq_id, status, check_project_id=False)
Should check the project ID before, esp if you're asking to skip the project check on update status

2022-06-06 03:20 UTC, vivbak commented
Closing as I believe this has actually been handled already 

- You can pull the appropriate sequence ID here, then update accordingly https://github.com/populationgenomics/sample-metadata/blob/96649a7d0d8e8836c0e7709a55b46d78b6f7f1d2/api/routes/sequence.py#L118

2022-06-06 03:20 UTC, closed without merging