Add participant fields
populationgenomics/sample-metadata pull request #188
Opened 2022-04-20 12:05 UTC by vivbak

2022-04-21 00:22 UTC, illusional requested changes

2022-04-21 00:22 UTC, illusional commented on sample_metadata/parser/generic_metadata_parser.py
> +        return 0
I think this should throw if it can't detect, not fall back to undefined - otherwise you might inadvertently lose data.

2022-04-21 00:22 UTC, illusional commented on sample_metadata/parser/generic_parser.py
> +        """Get karyotype from grouped row"""
Marking these as abstract requires the subclass to implement it, I think a default implementation of returning None should be fine. That will also stop the linting errors.

2022-04-21 00:22 UTC, illusional commented on sample_metadata/parser/generic_parser.py
> +        if reported_sex:
If reported_sex is `0` this will not work, maybe check for `is None`?

2022-04-21 00:23 UTC, illusional commented
I know it's annoying, but could you add a parser test to check that this works?

2022-05-02 11:47 UTC, vivbak commented
Thanks for calling out the lack of tests! Helped catch a few cases!

2022-05-02 22:08 UTC, illusional approved these changes
Nicely done! Tests LGTM!

2022-05-02 22:09 UTC, illusional commented
I've just merged dev in, so it can generate a coverage report - please don't merge until the codecov bot posts :)

2022-05-02 22:26 UTC, merged