Get Sequences By Criteria
populationgenomics/sample-metadata pull request #266
Opened 2022-08-08 22:50 UTC by vivbak

2022-08-17 03:10 UTC, vivbak commented
Oops sorry @illusional I thought I requested a review on this already 😅

2022-08-17 03:14 UTC, illusional requested changes

2022-08-17 03:14 UTC, illusional commented on api/routes/sequence.py
> +    active: bool = Body(default=True),
Why Body here, seems reasonable to keep this in the query params.

2022-08-17 03:15 UTC, illusional commented
Looks really great @vivbak, I've left a few questions + just need to make sure if project_ids aren't specified, we're correctly checking permissions on returned resources.

2022-08-19 02:34 UTC, illusional approved these changes
Amazing work! Can you add a bumpversion commit, and then this should be all sweet :)

2022-08-19 03:36 UTC, merged