Generic Metadata Parser Fixes
populationgenomics/sample-metadata pull request #455
Opened 2023-04-11 11:56 UTC by vivbak

Addresses https://github.com/populationgenomics/sample-metadata/issues/449 and https://github.com/populationgenomics/sample-metadata/issues/451

2023-04-11 12:05 UTC, vivbak commented
ah sorry ignore this for a sec @illusional

2023-04-12 04:15 UTC, illusional requested changes
I support the change, can you add tests to cover the existing_cohort parser please, especially important as I'm structurally changing the parsers and want to avoid regresssions.

2023-04-12 04:15 UTC, illusional commented on sample_metadata/parser/generic_metadata_parser.py
> +    '--karyotype_column',
```suggestion
    '--karyotype-column',
```

2023-04-19 00:09 UTC, illusional approved these changes

2023-04-19 00:16 UTC, merged